# Generated by Django 5.2.5 on 2025-08-07 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='会社コード')),
                ('name', models.CharField(max_length=255, verbose_name='会社名')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='インボイス番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='担当者名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '取引先会社',
                'verbose_name_plural': '取引先会社',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='自動連番')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='請求書番号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='請求金額')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='消費税額')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='合計金額')),
                ('invoice_date', models.DateField(verbose_name='請求日')),
                ('due_date', models.DateField(verbose_name='支払期限')),
                ('payment_status', models.CharField(choices=[('pending', '未払い'), ('paid', '支払済み'), ('overdue', '延滞')], default='pending', max_length=20, verbose_name='支払状況')),
                ('description', models.TextField(blank=True, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_management.company', verbose_name='取引先会社')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='ユーザーコード')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
    ]
