# Generated by Django 5.2.5 on 2025-08-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
